apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-ghee-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-ghee-backend
  template:
    metadata:
      labels:
        app: cv-ghee-backend
    spec:
      containers:
      - name: backend
        image: vasudhara12/cv-ghee-backend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: cv-ghee-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-ghee-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-ghee-frontend
  template:
    metadata:
      labels:
        app: cv-ghee-frontend
    spec:
      containers:
      - name: frontend
        image: vasudhara12/cv-ghee-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer   # ✅ CHANGED HERE
  selector:
    app: cv-ghee-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
