apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-ghee-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-ghee-frontend
  template:
    metadata:
      labels:
        app: cv-ghee-frontend
    spec:
      containers:
        - name: frontend
          image: vasudhara12/cv-ghee-frontend:latest
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: cv-ghee-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer            
